# modified from: wmt_ende_best.yaml
name: "gru_ende"

data:
    src: "en"
    trg: "de"
    train: "chatnmt/prep/train.tags.bpe.10000"
    dev: "chatnmt/prep/dev.tags.bpe.10000"
    test: "chatnmt/prep/test.tags.bpe.10000"
    level: "bpe"
    lowercase: False
    max_sent_length: 100
    src_voc_min_freq: 0
    src_voc_limit: 100000
    trg_voc_min_freq: 0
    trg_voc_limit: 100000
    #src_vocab: "test/data/en-de/vocab.txt"
    #trg_vocab: "test/data/en-de/vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.0002
    learning_rate_min: 0.0000005
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 4096
    batch_type: "token"
    scheduling: "plateau"
    patience: 4
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 100
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/gru_ende"
    overwrite: False
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2]

model:
    tied_embeddings: False #changed, check
    encoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 512
            scale: False
        hidden_size: 1024
        bidirectional: True
        dropout: 0.2
        num_layers: 4
    decoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 1024
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 4
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
