# modified from: transformer_wmt17_ende.yaml
name: "transformer"

data:
    src: "en"
    trg: "de"
    train: "chatnmt/prep/train_concat_prev.tags.bpe.10000"    # training data
    dev: "chatnmt/prep/dev_concat_prev.tags.bpe.10000"        # development data for validation
    test:  "chatnmt/prep/test_concat_prev.tags.bpe.10000"
    level: "bpe"
    lowercase: True ###changed, check
    max_sent_length: 100
    #src_vocab: "models/wmt_ende_transformer/src_vocab.txt"
    #trg_vocab: "models/wmt_ende_transformer/trg_vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 8
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    eval_batch_size: 3600
    eval_batch_type: "token"
    batch_multiplier: 1
    early_stopping_metric: "ppl"
    epochs: 100
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/transformer_ende"
    #load_model: "models/wmt_ende_transformer/best.ckpt"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3]
    keep_last_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: False #changed
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        freeze: False
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        freeze: False
        dropout: 0.1
